name: your_health_ex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  json_annotation: any
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  fl_chart: ^0.70.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/manrope/Manrope-Light.ttf
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
